name: check 
on:
  pull_request:
    branches: [ main ]
    paths: 'plugins/*'
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Check for the filename
      run: |
        find ./plugins/*/ -type f -name "*.plugin.js"
